# Generated by Django 2.2.5 on 2020-06-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='is_author',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=1),
        ),
    ]
